name: nationality_prediction
description: A new Flutter project to predict nationality of person based on his name.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  retrofit_generator: ^7.0.8
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  dio: ^5.3.2
  get_it: ^7.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  #  assets:
  #    - assets/images/

  #  fonts:
  #    - family: cairo
  #      fonts:
  #        - asset: assets/Cairo-Bold.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
